### ISSUE TITLE
zu locale is non-standard

### ISSUE THREAD

**Issue by MrRoyce** [sveltekit-i18n/lib#156] opened 2023-10-18 01:23 UTC
Hi all, I'm trying to add Zulu (zu) as a translation language but the library throws a warning 

`[i18n]: 'zu' locale is non-standard.`

Is there a list of valid languages?  Is there a way around this issue?

**Comment by ThibaultAndreis** [comment] 2023-10-19 09:09
This project use 
Intl.Collator.supportedLocalesOf()

a browser api to return the matching locals given a string

```javascript
Intl.Collator.supportedLocalesOf('zu')
```
return ``['zu']`` in firefox and in safari

Trying it on chrome return an empty array, even after having installed zulu on my computer




Seems to be a duplicate of  #109

> As far as the `mn` locale is not supported by `Intl.Collator.supportedLocalesOf` you could avoid console warnings for production like this:
> 
> ```ts
> import type { Config } from 'sveltekit-i18n';
> 
> const config: Config = {
>   // ...
>   log: {
>     level: process.env.NODE_ENV === 'production' ? 'error' : 'warn',
>   }
> };
> ```

**Comment by jarda-svoboda** [comment] 2023-11-13 21:15
This behavior is not being considered as an issue of this lib as it uses native JavaScript solution to differentiate between standard and non-standard locales.

**Closed by jarda-svoboda** 2023-11-13 21:15 UTC
