### ISSUE TITLE
Argument types do not match parameters

### ISSUE THREAD

**Issue by inta** [sveltekit-i18n/lib#37] opened 2022-02-16 08:01 UTC
If I use $t in a script element like this:
```
<script lang="ts">
	import {t} from '$lib/i18n';

	export let placeholder = $t('search.placeholder');
</script>
```
PhpStorm shows an error:
> Argument types do not match parameters

Placing it inside the template/HTML part …
```
<input placeholder={$t('search.placeholder')}/>
```
… does not.

I'm not sure this is a problem with sveltekit-i18n, but I have no idea why this happens. The translation is actually working, it is just the IDE complaining and marking files as erroneous.

**Comment by inta** [comment] 2022-02-16 08:26
Ok, seems like the typescript definition does not mark some of the parameters as optional.

**Comment by jarda-svoboda** [comment] 2022-02-16 10:56
Could you please share your config?

**Comment by inta** [comment] 2022-02-16 13:35
The config looks like:
```
import i18nKit from 'sveltekit-i18n';

/** @type {import('sveltekit-i18n').Config} */
const translationConfig = {
	loaders: [
		{
			locale: 'en',
			key: '',
			loader: async () => (
				await import('../../translations/en.json')
			).default,
		},
		{
			locale: 'de',
			key: '',
			loader: async () => (
				await import('../../translations/de.json')
			).default,
		},
	],
};

export const {t, locale, locales, loading, loadTranslations} = new i18nKit(translationConfig);
```
for now (separation into modules is planned, but not done yet).

In `__layout.svelte` I just call:
```
await loadTranslations(language, pathname);
locale.set(language);
```
inside the load function.

Version: 2.0.0-rc.6

**Comment by jarda-svoboda** [comment] 2022-02-16 21:14
it seems, you are using `.js` for your config and `lang="ts"` in `.svelte`, right? not sure yet if this might be the root cause...

**Comment by jarda-svoboda** [comment] 2022-02-16 22:46
It seems to be some issue related to `JetBrains IDE` + `.svelte` files...

In `.svelte` file:
```svelte
<script lang="ts">
    $t('some.placeholder'); // ===> Argument types do not match parameters
    t.get('some.placeholder'); // ===> Invalid number of arguments, expected 3
    
    $t('some.placeholder', undefined, undefined); // ===> Argument types do not match parameters 
    t.get('some.placeholder', undefined, undefined); // ===> NO ERROR...
</script>
```

In `$lib/i18n`:
```ts
t.get('some.key'); // ===> NO ERROR...
```

**Comment by jarda-svoboda** [comment] 2022-02-17 00:46
Closing this as it is most probably not a bug in this library. Please, correct me if i'm wrong..

**Closed by jarda-svoboda** 2022-02-17 00:46 UTC
Labels: bug

**Comment by inta** [comment] 2022-02-17 07:02
I think the problem appears inside the script element because it is set to typescript, the template area inside svelte-files seems to be handled as regular Javascript. The error goes away if I remove the lang attribute from the script element.

For me it seems like a type definition problem, but I'm not yet that firm with typescript and the defintion looks ok for me. So I'm not in the position to correct you...

**Comment by jarda-svoboda** [comment] 2022-02-17 07:38
Well, the weird thing is, that it worked in regular `.ts`..🤔
