### ISSUE TITLE
SEO friendlyness 

### ISSUE THREAD

**Issue by Swepool** [sveltekit-i18n/lib#77] opened 2022-05-26 08:59 UTC
_Using local-router_

When hitting "/" it should not redirect to "/defaultLocale" as this is not good for SEO. I believe when hitting defaultLocale it should not add "/defaultLocale" as it counts as a redirect and makes it's most of the times non-indexable.

**Comment by jarda-svoboda** [comment] 2022-05-26 09:10
I believe this is a duplicate of #72

**Closed by jarda-svoboda** 2022-05-26 09:10 UTC
